=== aparra/lexcomp/src/main/schemas/configuracao-urn.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.lexml.gov.br/schema/qc/configuracao-urn"
	xmlns:tns="http://www.lexml.gov.br/schema/qc/configuracao-urn"
	elementFormDefault="qualified">

	<element name="Configuracao" type="tns:Configuracao"></element>
	<complexType name="Configuracao">
		<sequence>
			<element name="Categorias" type="tns:Categorias"></element>
			<element name="Localidades" type="tns:Localidades"></element>
			<element name="Autoridades" type="tns:Autoridades"></element>
			<element name="TiposDocumentos" type="tns:TiposDocumentos">
			</element>
			<element name="Versoes" type="tns:Versoes"></element>
			<element name="Eventos" type="tns:Eventos"></element>
			<element name="Correlacoes" type="tns:Correlacoes"></element>
		</sequence>
	</complexType>
	<complexType name="Categorias">
		<sequence minOccurs="1" maxOccurs="unbounded">
			<element name="Categoria" type="tns:Categoria"></element>
		</sequence>
	</complexType>
	<complexType name="Localidades">
		<sequence minOccurs="1" maxOccurs="unbounded">
			<element name="Localidade" type="tns:Localidade" />
		</sequence>
	</complexType>
	<complexType name="Autoridades">
		<sequence minOccurs="1" maxOccurs="unbounded">
			<element name="Autoridade" type="tns:Autoridade" />
		</sequence>
	</complexType>
	<complexType name="TiposDocumentos">
		<sequence minOccurs="1" maxOccurs="unbounded">
			<element name="TipoDocumento" type="tns:TipoDocumento" />
		</sequence>
	</complexType>
	<complexType name="Versoes">
		<sequence minOccurs="1" maxOccurs="unbounded">
			<element name="Versao" type="tns:Versao" />
		</sequence>
	</complexType>
	<complexType name="Eventos">
		<sequence minOccurs="1" maxOccurs="unbounded">
			<element name="Evento" type="tns:Evento" />
		</sequence>
	</complexType>
	<complexType name="Correlacoes">
		<sequence minOccurs="1" maxOccurs="unbounded">
			<element name="Correlacao" type="tns:Correlacao" />
		</sequence>
	</complexType>
	<complexType name="Categoria">
		<complexContent>
			<extension base="tns:Vocabulo"></extension>
		</complexContent>
	</complexType>
	<complexType name="Localidade">
		<complexContent>
			<extension base="tns:Vocabulo"></extension>
		</complexContent>
	</complexType>
	<complexType name="Autoridade">
		<complexContent>
			<extension base="tns:Vocabulo">
				<sequence>
					<element name="SiglaColegiado" type="tns:Sigla" maxOccurs="1"
						minOccurs="0"></element>					
				</sequence>
				<attribute name="requerSigla" type="boolean" default="false"></attribute>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="TipoDocumento">
		<complexContent>
			<extension base="tns:Vocabulo">
				<sequence>
					<element name="SiglaDocumento" type="tns:Sigla" maxOccurs="1"
						minOccurs="0"></element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="Versao">
		<complexContent>
			<extension base="tns:Vocabulo">
				<attribute name="requerData" type="boolean" default="false" />
			</extension>
		</complexContent>
	</complexType>
	<complexType name="Evento">
		<complexContent>
			<extension base="tns:Vocabulo">
			<attribute name="requerData" type="boolean" default="false"/>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="Correlacao">
		<attribute name="categoria" type="string" use="required"/>
		<attribute name="localidade" type="string" use="required"/>
		<attribute name="autoridade" type="string" use="required"/>
		<attribute name="tipoDocumento" type="string" use="required"/>
		<attribute name="versao" type="string" use="optional"/>
		<attribute name="evento" type="string" use="optional"/>
		<attribute name="componenteColegiado" type="string" use="optional"/>
		<attribute name="componenteDocumento" type="string" use="optional"/>
	</complexType>

	<complexType name="Vocabulo" abstract="true">
		<sequence>
			<element name="Nome" type="string"></element>
		</sequence>
		<attribute name="xmlid" type="string" use="required"></attribute>
	</complexType>



	<complexType name="Sigla">
		<simpleContent>
			<extension base="string">
				<attribute name="urn" type="anyURI"></attribute>
			</extension>
		</simpleContent>
	</complexType>
</schema>

=== aparra/lexcomp/qc-presentation/web/xml/configuracao.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuracao xmlns="http://www.lexml.gov.br/schema/qc/configuracao-urn" 
              xmlns:xml="http://www.w3.org/XML/1998/namespace"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.lexml.gov.br/schema/qc/configuracao-urn ../../src/main/schemas/configuracao-urn.xsd">
    <Categorias>
        <Categoria xmlid="legislacao">
            <Nome>Legislação</Nome>
        </Categoria>
        <Categoria xmlid="proposicoes.legislativas.substitutivos">
            <Nome>Proposições Legislativas e Substitutivos</Nome>
        </Categoria>
        <Categoria xmlid="emendas">
            <Nome>Emendas</Nome>
        </Categoria>
        <Categoria xmlid="destaques">
            <Nome>Destaques</Nome>
        </Categoria>
    </Categorias>
    <Localidades>
        <Localidade xmlid="br">
            <Nome>Brasil</Nome>
        </Localidade>
        <Localidade xmlid="br;minas.gerais">
            <Nome>Minas Gerais</Nome>
        </Localidade>
        <Localidade xmlid="br;minas.gerais;belo.horizonte">
            <Nome>Belo Horizonte (MG)</Nome>
        </Localidade>
    </Localidades>
    <Autoridades>
        <Autoridade xmlid="federal">
            <Nome>Federal</Nome>
        </Autoridade>
        <Autoridade xmlid="estadual">
            <Nome>Estadual</Nome>
        </Autoridade>
        <Autoridade xmlid="municipal">
            <Nome>Municipal</Nome>
        </Autoridade>
        <Autoridade xmlid="distrital">
            <Nome>Distrital</Nome>
        </Autoridade>
        <Autoridade xmlid="congresso.nacional">
            <Nome>Congresso Nacional</Nome>
            <SiglaColegiado urn="cn">CN</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="congresso.nacional;senado.federal">
            <Nome>Senado Federal</Nome>
            <SiglaColegiado urn="sf">SF</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="congresso.nacional;camara.deputados">
            <Nome>Câmara dos Deputados</Nome>
            <SiglaColegiado urn="cd">CD</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="senado.federal">
            <Nome>Senado Federal</Nome>
            <SiglaColegiado urn="sf">SF</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="camara.deputados">
            <Nome>Câmara dos Deputados</Nome>
            <SiglaColegiado urn="cd">CD</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="assembleia.legislativa">
            <Nome>Assembleia Legislativa</Nome>
        </Autoridade>
        <Autoridade xmlid="camara.municipal">
            <Nome>Câmara Municipal</Nome>
        </Autoridade>
        
        <Autoridade xmlid="senado.federal;plenario">
            <Nome>Plenário</Nome>
            <SiglaColegiado urn="plen">PLEN</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="senado.federal;comissao.assuntos.economicos">
            <Nome>Comissão de Assuntos Econômicos</Nome>
            <SiglaColegiado urn="cae">CAE</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="senado.federal;comissao.assuntos.sociais">
            <Nome>Comissão de Assuntos Sociais</Nome>
            <SiglaColegiado urn="cas">CAS</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="senado.federal;comissao.constituicao.justica.cidadania">
            <Nome>Comissão de Constituição, Justiça e Cidadania</Nome>
            <SiglaColegiado urn="ccj">CCJ</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="senado.federal;comissao.educacao.cultura.esporte">
            <Nome>Comissão de Educação, Cultura e Esporte</Nome>
            <SiglaColegiado urn="ce">CE</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="senado.federal;comissao.meio.ambiente.defesa.consumidor.fiscalizacao.controle">
            <Nome>Comissão de Meio Ambiente, Defesa do Consumidor e Fiscalização e Controle</Nome>
            <SiglaColegiado urn="cma">CMA</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="senado.federal;comissao.direitos.humanos.legislacao.participativa">
            <Nome>Comissão de Direitos Humanos e Legislação Participativa</Nome>
            <SiglaColegiado urn="cdh">CDH</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="senado.federal;comissao.relacoes.exteriores.defesa.nacional">
            <Nome>Comissão de Relações Exteriores e Defesa Nacional</Nome>
            <SiglaColegiado urn="cre">CRE</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="senado.federal;comissao.servicos.infraestrutura">
            <Nome>Comissão de Serviços de Infraestrutura</Nome>
            <SiglaColegiado urn="ci">CI</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="senado.federal;comissao.desenvolvimento.reginoal.turismo">
            <Nome>Comissão de Desenvolvimento Regional e Turismo</Nome>
            <SiglaColegiado urn="cdr">CDR</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="senado.federal;comissao.agricultura.reforma.agraria">
            <Nome>Comissão de Agricultura e Reforma Agrária</Nome>
            <SiglaColegiado urn="cra">CRA</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="senado.federal;comissao.ciencia.tecnologia.inovacao.comunicacao.informatica">
            <Nome>Comissão de Ciência, Tecnologia, Inovação, Comunicação e Informática</Nome>
            <SiglaColegiado urn="cct">CCT</SiglaColegiado>
        </Autoridade>
        

        <Autoridade xmlid="camara.deputados;plenario">
            <Nome>Plenário</Nome>
            <SiglaColegiado urn="plen">PLEN</SiglaColegiado>
        </Autoridade>
        
        <Autoridade xmlid="camara.deputados;comissao.constituicao.justica.cidadania">
            <Nome>Comissão Constituição Justiça e Cidadania</Nome>
            <SiglaColegiado urn="ccjc">CCJC</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="camara.deputados;comissao.viacao.transporte">
            <Nome>Comissão Viação e Transporte</Nome>
            <SiglaColegiado urn="cvt">CVT</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="camara.deputados;comissao.amazonia.integracao.nacional.desenvolvimento.regional">
            <Nome>Comissão da Amazônia, Integração Nacional e de Desenvolvimento Regional</Nome>
            <SiglaColegiado urn="caindr">CAINDR</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="camara.deputados;comissao.agricultura.pecuaria.abastecimento.desenvolvimento.rural">
            <Nome>Comissão de Agricultura, Pecuária, Abastecimento e Desenvolvimento Rural</Nome>
            <SiglaColegiado urn="capadr">CAPADR</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="camara.deputados;comissao.ciencia.tecnologia.comunicacao.informatica">
            <Nome>Comissão de Ciência e Tecnologia, Comunicação e Informática</Nome>
            <SiglaColegiado urn="cctci">CCTCI</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="camara.deputados;comissao.defesa.consumidor">
            <Nome>Comissão de Defesa do Consumidor</Nome>
            <SiglaColegiado urn="cdc">CDC</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="camara.deputados;comissao.desenvolvimento.economico.industria.comercio">
            <Nome>Comissão de Desenvolvimento Econômico, Indústria e Comércio</Nome>
            <SiglaColegiado urn="cdeic">CDEIC</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="camara.deputados;comissao.desenvolvimento.urbano">
            <Nome>Comissão de Desenvolvimento Urbano</Nome>
            <SiglaColegiado urn="cdu">CDU</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="camara.deputados;comissao.direitos.humanos.minorias">
            <Nome>Comissão de Direitos Humanos e Minorias</Nome>
            <SiglaColegiado urn="cdhm">CDHM</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="camara.deputados;comissao.educacao.cultura">
            <Nome>Comissão de Educação e Cultura</Nome>
            <SiglaColegiado urn="cec">CEC</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="camara.deputados;comissao.financas.tributacao">
            <Nome>Comissão de Finanças e Tributação</Nome>
            <SiglaColegiado urn="cft">CFT</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="camara.deputados;comissao.fiscalizacao.financeira.controle">
            <Nome>Comissão de Fiscalização Financeira e Controle</Nome>
            <SiglaColegiado urn="cffc">CFFC</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="camara.deputados;comissao.legislacao.participativa">
            <Nome>Comissão de Legislação Participativa</Nome>
            <SiglaColegiado urn="clp">CLP</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="camara.deputados;comissao.meio.ambiente.desenvolvimento.sustentavel">
            <Nome>Comissão de Meio Ambiente e Desenvolvimento Sustentável</Nome>
            <SiglaColegiado urn="cmads">CMADS</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="camara.deputados;comissao.minas.energia">
            <Nome>Comissão de Minas e Energia</Nome>
            <SiglaColegiado urn="cme">CME</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="camara.deputados;comissao.relacoes.exteriores.defesa.nacional">
            <Nome>Comissão de Relações Exteriores e de Defesa Nacional</Nome>
            <SiglaColegiado urn="credn">CREDN</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="camara.deputados;comissao.seguranca.publica.combate.crime.organizado">
            <Nome>Comissão de Segurança Pública e Combate ao Crime Organizado</Nome>
            <SiglaColegiado urn="cspcco">CSPCCO</SiglaColegiado>
        </Autoridade>
        <Autoridade xmlid="camara.deputados;comissao.seguridade.social.familia">
            <Nome>Comissão de Seguridade Social e Família</Nome>
